export const FOLLOWER_REGISTER = 'FOLLOWER_REGISTER';
export const PROVIDER_REGISTER = 'PROVIDER_REGISTER';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const TRADER_LOADED = 'TRADER_LOADED';
